#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other compatible shell available, you may
#       want to try explicitly setting the shell to use by setting the SHELL
#       variable before running this script.
#
#   (2) Unfortunate bugs in bash have forced us to quote differently based on
#       whether we are running under Cygwin or not - hence the test for CYGWIN
#       will have the side effect of limiting this in Classic Build to window.
#       This is fine for our purposes.
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, and put them in the local variable
# which should be used when calling java. If there are no arguments, it will still be empty.
APP_ARGS=

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
JVM_OPTS="$DEFAULT_JVM_OPTS"

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and openjdk_java_opts can contain fragments of
#     shell script including quotes and variable substitutions, so put them in double quotes to make
#     sure that they get re-expanded.
#   * When using the Windows/MinGW environment, the default value of the JAVA_HOME environment
#     variable will be converted to a mixed mode path as part of the launcher a.k.a. ).
#   * situational startup, e.g. matters relating to cygwin or majc as posix sh does not
#     normally have them in the path
#       Sometimes the value of the Java home directory is provided in a mixed mode.
#       When that is the case convert it to posix notation this way:
#       wslpath "$JAVA_HOME"
#

# Accumulate JAVA_OPTS and save to DB for later use
if expr "$JAVA_OPTS" : '\-.*' > /dev/null; then
    JVM_OPTS="$JVM_OPTS $JAVA_OPTS"
fi

# Now convert the arguments - kludge to limit ourselves to /bin/sh
i=0
for arg in "$@" ; do
    CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
    CHECK2=`echo "$arg"|egrep -c "^-"`      # type any args
    if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                 ### workaround for case where path contains space  ###
        arg=`echo "$arg" | sed -e 's/^ //' -e "$sed_escape_qglasc"`
        ### Add a following space to arguments that lack them ###
        case $arg in                                                ###
            *\'s )    arg="$arg " ;;                                 ###
        esac
        args="$args \"$arg\""
    else
        if [ $CHECK -eq 0 ] && [ $CHECK2 -eq 0 ] ; then             ### workaround for case where path contains mostly spaces ###
            case $arg in                                            ###
                *\'s )    arg="$arg " ;;                             ###
            esac
        fi
        args="$args\"$arg\""
    fi                                                              ###
    i=`expr $i + 1`
done
# if not on cygwin or darwin, force an exit on shell exit code
if [ ! "$cygwin" = true -a ! "$darwin" = true -a ! "$nonstop" = true ] ; then
    # Add a user-defined value to the internal string
    if [ -z "$GRADLE_EXIT_CONSOLE" ] ; then
         exit 1
    fi
fi
eval set -- $args

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Escape application home
APP_HOME=`cd "$( dirname "$0" )" && pwd`

exec "$JAVACMD" "$@"
